---
title: "That's a Spicy Sauce"
author: "David Jackson"
date: "5/23/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyr)
library(dplyr)
library(ggplot2)
library(scales)
```

### Demo of Data Pasta: Using Florida Census Data 

```{r}
rm(list=ls())

FL <- tibble::tribble(
                  ~Age,       ~Population,  ~Percent,
      "Under 5 years",    945823,  5.9,
       "5 to 9 years",   1031718,  6.5,
     "10 to 14 years",   1057024,  6.6,
     "15 to 19 years",   1014067,  6.3,
     "20 to 24 years",    928310,  5.8,
     "25 to 34 years",   2084100,   13,
     "35 to 44 years",   2485247, 15.5,
     "45 to 54 years",   2069479, 12.9,
     "55 to 59 years",    821517,  5.1,
     "60 to 64 years",    737496,  4.6,
     "65 to 74 years",   1452176,  9.1,
     "75 to 84 years",   1024134,  6.4,
  "85 years and over",    331287,  2.1
  )
```
```{r}
##  Pull First Age.
FL$Year <- readr::parse_number(FL$Age)
summary(FL)
```

### Plot by Age Group

```{r}


ggplot(FL) + geom_col(aes(x=reorder(Age,Population),y=Population)) +
  scale_y_continuous(labels =  comma) +
  theme(axis.text.x = element_text(angle = 45))

FL$Year <- as.factor(FL$Year)
ggplot(FL) + geom_col(aes(x=Year,y=Population)) +
  scale_y_continuous(labels =  comma) +
  labs(title = "Population by Age",x="Age in Years",y="Population",
       caption = "Source: https://www.infoplease.com/")
```

### Age Group Population as a Percent of Total 

```{r}
FL$Rate <- FL$Percent/100
ggplot(FL) + geom_col(aes(x=reorder(Age, Rate),y=Rate)) +
  scale_y_continuous(labels =  percent) +
  theme(axis.text.x = element_text(angle = 45)) + 
  labs(title = "Population by Age and Percent",x="Age in Years",y="By Percent by Age",
       caption = "Source: https://www.infoplease.com/")
```

#### (The End)